import { AppProviders } from "@/app/providers";
import { theme } from "@/theme";
import { ColorModeScript } from "@chakra-ui/color-mode";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type { PropsWithChildren } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ColorModeScript initialColorMode={theme.config.initialColorMode} />
				<AppProviders>{children}</AppProviders>
			</body>
		</html>
	);
}
